### ISSUE TITLE
Create SFC fails trying to create folder /c:/...

### ISSUE THREAD

**Issue by Jogai** [AttilioCapocchiani/vuejs-vscode-helper#2]
I think it fails because its trying to create a path starting with c: instead of creating a folder in c:

`Command 'Vue SFC Editor: Create SFC' resulted in an error (ENOENT: no such file or directory, mkdir '/c:/SRC/ACRO/Full.Platform.Web/clientapp/src/views')`

Obviously, I'm using windows...

**Comment by AttilioCapocchiani** [comment]
Hi @Jogai,

sorry if I didn't answer earlier but I just noticed this issue. Can you provide me the full path from which you are trying to create the component so I can try to reproduce the error? It should be an existing SFC.

**Comment by Jogai** [comment]
The full path is in the error message. What do you mean about "existing SFC"? Same thing happens if I try from a new vue file in the views folder.

**Comment by AttilioCapocchiani** [comment]
@Jogai thank you. I should have released a new version (1.2.2) that should solve this problem under Windows. I closed the issue. Feel free to re-open or comment if this didn't work.

Thank you,
Attilio
